[dotnet-trace] Add collect-linux verb (#5570)
Implements https://github.com/dotnet/docs/pull/47894

Following the addition of emitting native runtime and custom EventSource
events as user_events through
https://github.com/dotnet/runtime/pull/115265 and the public release of
https://github.com/microsoft/one-collect which supports collecting both
.NET user_events and Linux perf events into a single .nettrace file,
`dotnet-trace` will support a new verb, `collect-linux`, that wraps
around `record-trace`.

This PR does the following:
- Adds `collect-linux` verb and serializes a subset of `dotnet-trace
collect` options in addition to a `collect-linux` specific
`--perf-events` option into `record-trace` args. (see
https://github.com/dotnet/docs/pull/47894 for overarching details)
- Adds record-trace dynamic library to `dotnet-trace`
- Updates existing profiles (`cpu-sampling` -> `dotnet-common` +
`dotnet-sampled-thread-time`) and adds `collect-linux` specific profiles
- Updates `list-profiles` verb with revamped profiles + multiline
description formatting
- Refactors `EventPipeProvider` composition logic
(`MergeProfileAndProviders` + `ToProviders` -> `ComputeProviderConfig`)
and rename `Extensions.cs` -> `ProviderUtils.cs`
- Revamp EventPipeProvider composition tests (`ProviderParsing.cs` ->
`ProviderCompositionTests.cs`)
- Various cleanup: Update CLREventKeywords + Update logging + refactor
`collect` logic + expand `dotnet-trace` common options

## Testing

### dotnet-trace collect-linux

On Linux
<details>
<summary>collect-linux</summary>
<details>
  <summary>collect-linux --help</summary>

```bash
$ ./dotnet-trace collect-linux -h
Description:
  Collects diagnostic traces using perf_events, a Linux OS technology. collect-linux requires admin privileges to capture kernel- and user-mode events, and by default, captures events from
  all processes. This Linux-only command includes the same .NET events as dotnet-trace collect, and it uses the kernel’s user_events mechanism to emit .NET events as perf events, enabling
  unification of user-space .NET events with kernel-space system events.

Usage:
  dotnet-trace collect-linux [options]

Options:
  --providers      A comma delimited list of EventPipe providers to be enabled. This is in the form 'Provider[,Provider]',where Provider is in the form:
                   'KnownProviderName[:[Flags][:[Level][:[KeyValueArgs]]]]', and KeyValueArgs is in the form: '[key1=value1][;key2=value2]'.  Values in KeyValueArgs that contain ';' or '='
                   characters need to be surrounded by '"', e.g., FilterAndPayloadSpecs="MyProvider/MyEvent:-Prop1=Prop1;Prop2=Prop2.A.B;".  Depending on your shell, you may need to escape
                   the '"' characters and/or surround the entire provider specification in quotes, e.g., --providers
                   'KnownProviderName:0x1:1:FilterSpec=\"KnownProviderName/EventName:-Prop1=Prop1;Prop2=Prop2.A.B;\"'. These providers are in addition to any providers implied by the
                   --profile argument. If there is any discrepancy for a particular provider, the configuration here takes precedence over the implicit configuration from the profile.  See
                   documentation for examples.
  --clreventlevel  Verbosity of CLR events to be emitted.
  --clrevents      List of CLR runtime events to emit.
  --perf-events    Comma-separated list of perf events (e.g. syscalls:sys_enter_execve,sched:sched_switch).
  --profile        A named, pre-defined set of provider configurations for common tracing scenarios. You can specify multiple profiles as a comma-separated list. When multiple profiles are
                   specified, the providers and settings are combined (union), and duplicates are ignored.
  -o, --output     The output path for the collected trace data. If not specified it defaults to '<appname>_<yyyyMMdd>_<HHmmss>.nettrace', e.g., 'myapp_20210315_111514.nettrace'. [default:
                   default]
  --duration       When specified, will trace for the given timespan and then automatically stop the trace. Provided in the form of dd:hh:mm:ss.
  -?, -h, --help   Show help and usage information
```
</details>
<details>
<summary>`collect-linux` without elevated privileges</summary>

```bash
$ ./dotnet-trace collect-linux
==========================================================================================
The collect-linux verb is in preview. Some usage scenarios may not yet be supported,
and some trace parsers may not yet support NetTrace V6. For any bugs or unexpected
behaviors, please open an issue at https://github.com/dotnet/diagnostics/issues.
==========================================================================================
No providers, profiles, ClrEvents, or PerfEvents were specified, defaulting to trace profiles 'dotnet-common' + 'cpu-sampling'.

Provider Name                           Keywords            Level               Enabled By
Microsoft-Windows-DotNETRuntime         0x000000100003801D  Informational(4)    --profile

Linux Perf Events                                                               Enabled By
cpu-sampling                                                                    --profile

Output File    : /home/mihw/repo/diagnostics/trace_20251022_152234.nettrace

Error: Tracefs is not accessible: Permission denied (os error 13)
```
</details>
<details>
<summary>`collect-linux` with elevated privileges</summary>

```bash
$ sudo ./dotnet-trace collect-linux
==========================================================================================
The collect-linux verb is in preview. Some usage scenarios may not yet be supported,
and some trace parsers may not yet support NetTrace V6. For any bugs or unexpected
behaviors, please open an issue at https://github.com/dotnet/diagnostics/issues.
==========================================================================================
No providers, profiles, ClrEvents, or PerfEvents were specified, defaulting to trace profiles 'dotnet-common' + 'cpu-sampling'.

Provider Name                           Keywords            Level               Enabled By
Microsoft-Windows-DotNETRuntime         0x000000100003801D  Informational(4)    --profile

Linux Perf Events                                                               Enabled By
cpu-sampling                                                                    --profile

Output File    : /home/mihw/repo/diagnostics/trace_20251022_152124.nettrace

[00:00:00:21]   Recording trace.
Press <Enter> or <Ctrl-C> to exit...
Recording stopped.
Resolving symbols.
Finished recording trace.
Trace written to /home/mihw/repo/diagnostics/trace_20251022_152124.nettrace
```
</details>
</details>

On Windows (and I presume other non-Linux OS):
<details>
<summary>`collect-linux`</summary>

```pwsh
.\artifacts\bin\dotnet-trace\Debug\net8.0\dotnet-trace.exe collect-linux
The collect-linux command is only supported on Linux.
```
</details>

### dotnet-trace list-profiles

<details>
<summary>`list-profiles`</summary>

```bash
dotnet-trace profiles:
        dotnet-common                        - Lightweight .NET runtime diagnostics designed to stay low overhead.
                                               Includes GC, AssemblyLoader, Loader, JIT, Exceptions, Threading, JittedMethodILToNativeMap, and Compilation events
                                               Equivalent to --providers "Microsoft-Windows-DotNETRuntime:0x100003801D:4".
        dotnet-sampled-thread-time (collect) - Samples .NET thread stacks (~100 Hz) toestimate how much wall clock time code is using.
        gc-verbose                           - Tracks GC collections and samples object allocations.
        gc-collect                           - Tracks GC collections only at very low overhead.
        database                             - Captures ADO.NET and Entity Framework database commands
        cpu-sampling (collect-linux)         - Kernel CPU sampling events for measuring CPU usage.
        thread-time (collect-linux)          - Kernel thread context switch events for measuring CPU usage and wall clock time
```
</details>

<img width="215" height="172" alt="Screenshot 2025-09-19 142848"
src="https://github.com/user-attachments/assets/9229b2f0-92fa-4c87-89e7-505c55f7ae6a"
/>
<img width="730" height="1049" alt="Screenshot 2025-09-19 142945"
src="https://github.com/user-attachments/assets/4be3f222-0495-4f93-979c-43d68cd5f964"
/>
<img width="1903" height="823" alt="Screenshot 2025-09-19 142858"
src="https://github.com/user-attachments/assets/370648f8-a5b5-436e-a9dc-73bffa0b2ad4"
/>